name: Android Emulator Workflow with noVNC-2

on:
  workflow_dispatch:  # Trigger manually from the GitHub Actions tab

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [29]  # API levels for Android Emulator

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Enable KVM for hardware acceleration
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Cache Android SDK and AVD
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      # noVNC Setup Steps
      - name: Install and set up noVNC for emulator viewing
        run: |
          sudo apt-get update
          sudo apt-get install -y x11vnc fluxbox websockify
          sudo apt-get install -y xfce4 xfce4-terminal
          wget https://github.com/novnc/noVNC/archive/v1.2.0.tar.gz
          tar -xzf v1.2.0.tar.gz
          mv noVNC-1.2.0 noVNC
          nohup xfce4-session &  # Start desktop environment
          nohup x11vnc -forever -usepw -create &  # Start VNC server
          nohup websockify --web /noVNC --wrap-mode ignore -- 6080 localhost:5900 &  # Start noVNC server

      - name: Start ngrok for noVNC
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-v3-stable-linux-amd64.zip
          unzip ngrok-v3-stable-linux-amd64.zip
          ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ./ngrok http 6080

      - name: Run tests on Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck

      - name: Display access URL for noVNC
        run: |
          echo "Access noVNC via ngrok URL"
